#ifndef MODULES_PRINTAVERAGEOFHOTTESTHOUROFTHEMONTH_H
#define MODULES_PRINTAVERAGEOFHOTTESTHOUROFTHEMONTH_H

void printAverageOfHottestHourOfTheMonth(float **array, int days, int measurements);

#endif //MODULES_PRINTAVERAGEOFHOTTESTHOUROFTHEMONTH_H
